steps:
    - name: 'gcr.io/cloud-builders/npm'
      dir: hackstr
      args: ['install']
    - name: 'gcr.io/cloud-builders/npm'
      dir: hackstr
      args: ['run', 'build']
    - name: 'gcr.io/cloud-builders/gcloud'
      dir: hackstr/build
      entrypoint: 'gsutil'
      args: ['cp', '-r', '.', 'gs://hackstr.couchforce.com']