steps:
  # send notification to slack
    - name: 'gcr.io/cloud-builders/curl'
      dir: hackstr
      args: ['-X', 'POST', "--data-urlencode", "payload={\"channel\": \"#hackster-cicd\", \"username\": \"webhookbot\", \"text\": \" Building react to hackster.couchforce.com\", \"icon_emoji\": \":ghost:\"}", "https://hooks.slack.com/services/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"]
    - name: 'gcr.io/cloud-builders/npm'
      dir: hackstr
      args: ['install']
    - name: 'gcr.io/cloud-builders/npm'
      dir: hackstr
      args: ['run', 'build']
    - name: 'gcr.io/cloud-builders/gcloud'
      dir: hackstr/build
      entrypoint: 'gsutil'
      args: ['cp', '-r', '.', 'gs://hackstr.couchforce.com']

 